### ISSUE TITLE
useToggle

### ISSUE THREAD

**Issue by xeptao** [rhymojs/rhymojs#26]
## Explain the feature

A custom toggle that returns a boolean value.

**Comment by swarup4741** [comment]
can i work on this feature ? 

I was just trying `useLocalStorage` and saw that it didn't persist the value on page refresh and I fixed your code on my local machine but then i discovered that u already have fixed that issue 4 days ago 😄 .... By the way you are building a great library of utility functions.. 💪🏼 which are really useful in day to day development

**Comment by xeptao** [comment]
Feel free to work on it. You don't have to ask me. Just open a pull request.

**Comment by xeptao** [comment]
@swarup4741 I plan adding you in the @rhymojs organization after a few contributions you make.

**Comment by xeptao** [comment]
Adding the "worked on" label because you are working on it

**Comment by swarup4741** [comment]
what should be the functionality of this `useToggle` ?  Will it return a stateful value and a setState function to toggle between true and false ? (please explain briefly)

**Comment by xeptao** [comment]
Instead of doing something like:

```tsx
const [toggle, setToggle] = useState(initialState);

// reverse the value
setToggle(previousValue => !previousValue);
```
You do:
```tsx
const [state, setState] = useToggle(initialState);
```

Not a lot but it is shorter.

**Comment by xeptao** [comment]
Or maybe could be useful in a situation like:

```tsx
const [isDarkTheme, reverseTheme] = useToggle(false);

<button onClick={reverseTheme}>{isDarkTheme ? "Convert to Light theme" : "Convert to Dark theme"}</button>
```

**Comment by xeptao** [comment]
You get me right? The entire point of this library is avoiding repetitive code. And this achieves it.

**Comment by swarup4741** [comment]
> Or maybe it could be useful in a situation like:
> 
> ```tsx
> const [isDarkTheme, reverseTheme] = useToggle(false);
> 
> <button onClick={reverseTheme}>{isDarkTheme ? "Convert to Light theme" : "Convert to Dark theme"}</button>
> ```

This can be used to make `useTheme` hook where we can use `useLocalStorage` to store the current theme

**Comment by xeptao** [comment]
Yes! This library avoids repetitive code and it helps itself not repeat code as well!

**Comment by xeptao** [comment]
Anways, I'll be sleeping now, gonna be looking at your PR tomorrow, good night!

**Comment by swarup4741** [comment]
i have passed the test
<img width="450" alt="test" src="https://user-images.githubusercontent.com/69234404/126027415-7447e4b7-de5f-4f55-b127-6d2dc2a208fd.PNG">

but still while commit the changes im getting this error
<img width="620" alt="usetoggle" src="https://user-images.githubusercontent.com/69234404/126027425-420b7756-457e-45a2-b404-8b056e613600.PNG">

my commit message is `Added a new feature - useToggle`
can you please help me out with this

**Comment by xeptao** [comment]
you have to follow conventional commits for ypur commit messages

**Comment by xeptao** [comment]
in your case this eouls be "feat: useToggle", which means a a new feature with the name of useToggle

**Comment by xeptao** [comment]
if it still doesn't commit, just push ypur changes to your fork and I'll look at it.

**Comment by xeptao** [comment]
I get it now, since you staged `useToggle.ts`, the git hook runs `yarn test src/useToggle.ts` which is not a test. Please push your tests before the feature with the commit message of `test: useToggle`

**Comment by xeptao** [comment]
Hey, I just implemented a script called `test:related` which only tests the latest tests, please update your fork.

**Comment by xeptao** [comment]
Thanks for your first contribution!
