### ISSUE TITLE
useTheme

### ISSUE THREAD

**Issue by xeptao** [rhymojs/rhymojs#27]
## Explain the feature

Allows you to toggle between light and dark themes and remembers it from local storage.

**Comment by swarup4741** [comment]
now will work on this feature 😄  ... it might take some time cause my university exams are near...

**Comment by xeptao** [comment]
Ok, I'll try to advertise the repo and get more contributors 😄

**Comment by swarup4741** [comment]
is rhymojs website not active now ?

**Comment by xeptao** [comment]
Yup, while writing a lot of boilerplate for testing and stuff, I barely started writing the code for the website. It's gonna be a MEMN (MERN but the R is NextJS) stack website with blogs, etc. The repo for it is @rhymojs/rhymojs.com

**Comment by swarup4741** [comment]
Ha

> Yup, while writing a lot of boilerplate for testing and stuff, I barely started writing the code for the website. It's gonna be a MEMN (MERN but the R is NextJS) stack website with blogs, etc. The repo for it is https://github.com/rhymojs/rhymojs.com

Have you planned any design system (structure) for the website ?
Cause I'm really interested to build it with you ?

**Comment by xeptao** [comment]
I already created the sitemap, now I am planning to document features.

**Comment by xeptao** [comment]
https://dev.to/xeptao/12-steps-to-creating-a-serious-startup-1lm3 - I am following my own blog and we are on the 5th step

**Comment by xeptao** [comment]
This is the sitemmap:

![20210717_132428.jpg](https://user-images.githubusercontent.com/77933875/126034002-8db882d2-e14c-4fdb-bad4-9638dc554cbd.jpg)

**Comment by xeptao** [comment]
The paths with the [brackets] are dynamic routes

**Comment by xeptao** [comment]
Maybe i could create a markdown file for the sitemap, would be a lot more professional :D

**Comment by swarup4741** [comment]
I thought of it something like this... 

```tsx
const useTheme = (): SwitchTheme => {
   const [theme, setTheme] = useLocalStorage('theme');
   const [toggle, reverseToggle] = useToggle(theme !== "" ? theme === 'light' ? false : true : false);

   const themeSwitcher = () => reverseToggle()

   if(theme)
   {
       document.body.parentElement?.setAttribute('data-theme',theme)
   }

   useEffect(() =>{
       setTheme(toggle ? 'dark' : 'light')
   },[toggle]);

   return [theme, () => themeSwitcher()];

}

```

**Comment by xeptao** [comment]
Seems pretty good, what code editor do you use by the way?

**Comment by swarup4741** [comment]
> Seems pretty good, what code editor do you use by the way?

VS code

**Comment by xeptao** [comment]
I do, do you use ESLint, because I setup prettier with it and it formats ts, and tsx extensions

**Comment by swarup4741** [comment]
> I do, do you use ESLint, because I setup prettier with it and it formats ts, and tsx extensions

yeah i do

**Comment by xeptao** [comment]
Ok, please change your default formatter to EsLint so it can format files

**Comment by xeptao** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?247F762AE52827AAE8B52C566E7128105A6E - live share link

**Comment by swarup4741** [comment]
> Ok, please change your default formatter to EsLint so it can format files

i have set it to default previously and i also i have joined the live share session

**Comment by xeptao** [comment]
ok, come to the file i'm editing

**Comment by xeptao** [comment]
Hey, do you see the file?

**Comment by xeptao** [comment]
ok, i'm starting another session

**Comment by xeptao** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?B6E9A47D7CEFAE96B325889579A7DA2D00C7

**Comment by swarup4741** [comment]
> ok, i'm starting another session

okkk
