### ISSUE TITLE
Links in README.md are broken

### ISSUE THREAD

**Issue by swarup4741** [rhymojs/rhymojs#66]
### Some Links in the `README.md` are broken
For example `Contributing.md`, `Report a bug` etc...

**Comment by xeptao** [comment]
Thanks for your contribution, I will creating a pull request for this.

**Comment by xeptao** [comment]
How did you find this project? I want to focus on that platform.

**Comment by swarup4741** [comment]
I was searching for issues related to TS and i came across this repo... Hope to contribute more in the upcoming days
