### ISSUE TITLE
useFetch

### ISSUE THREAD

**Issue by swarup4741** [rhymojs/rhymojs#81]
**Is your feature request related to a problem? Please describe.**
 Fetching data from an API endpoint and handling the promise becomes sometimes painful...

**Describe the solution you'd like**
create a useFetch hook which accepts an API endpoint and returns back the data , the loading state and also error (if any) 

**Describe alternatives you've considered**
I had to use javascript fetch method and handling promises was painful and also a loading state...

**Comment by xeptao** [comment]
There is a hook that already does this. It's `useQuery`, it handles the promise and throws an error if the provided string is not a URL. If you want it to use more than `GET`, you can create a PR.
