### ISSUE TITLE
`@rhymo/vanilla`

### ISSUE THREAD

**Issue by xeptao** [rhymojs/rhymojs#86]
**Is your feature request related to a problem? Please describe.**
Can't use this library in vanilla JavaScript but the same thing could be achieved.

**Describe the solution you'd like**
I would like a version of Rhymo called `@rhymo/vanilla` to be created.

**Describe alternatives you've considered**
Using it with React.

**Comment by swarup4741** [comment]
@xeptao i hope this can help [https://mohebifar.github.io/vidact/](https://mohebifar.github.io/vidact/) to convert the React code to simple Vanilla JS code

**Comment by xeptao** [comment]
Since the slogan of this library is "Avoid writing repetitive **React** code.", it's targeted against React users. Will not work on this.
